version: '3.7'
services:
  malware-document-scanner:
    build:
      context: ./malware-document-scanner
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
      - "9890:9890"
    container_name: malware-document-scanner
    volumes:
      - "./suspicious-files:/var/www/html"

networks:
  default:
    name: test
    external: true
