version: '3.7'
services:
  melware-document-scanner:
    build:
      context: ./melware-document-scanner
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
      - "9890:9890"
    container_name: melware-document-scanner


networks:
  default:
    name: test
    external: true
